name: Ocelot

on:
  workflow_dispatch:

jobs:
  ocelot:
    name: ocelot
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: Clone/compile gpuocelot
        run: |
          git clone https://github.com/gpuocelot/gpuocelot.git ${{ github.workspace }}/gpuocelot
          cd ${{ github.workspace }}/gpuocelot
          git submodule init
          git submodule update
          cd ocelot
          mkdir build
          cd build
          sudo apt-get install -y g++ cmake ninja-build llvm-15-dev libz-dev libglew-dev flex bison libfl-dev libboost-thread-dev libboost-filesystem-dev nvidia-cuda-toolkit-gcc libzstd-dev
          cmake .. -DBUILD_LLVM=ON -DBUILD_TESTS_CUDA=OFF
          make -j12
      - name: Install gpuocelot
        run: |
          cd ${{ github.workspace }}/gpuocelot/ocelot/build
          sudo cp libgpuocelot.so /usr/lib/libgpuocelot.so