name: Tests

env:
  PYTHONPATH: .

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  tests:
    name: tests
    runs-on: macos-14
    timeout-minutes: 20
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2 # NOTE: this fetches the HEAD commit of the PR
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Cache python packages
      uses: actions/cache@v4
      with:
        path: /Users/runner/Library/Python/3.11/lib/python/site-packages
        key: metal-m1-testing-user3-packages-${{ hashFiles('**/setup.py') }}
    - name: Cache downloads
      uses: actions/cache@v4
      with:
        path: ~/Library/Caches/tinygrad/downloads/
        key: downloads-cache-metal-only-${{ env.DOWNLOAD_CACHE_VERSION }}
    - name: Install Dependencies
      run: pip install numpy
    - name: Check Device.DEFAULT (METAL) and print some source
      run: | 
        git clone https://github.com/mesozoic-egg/tinygrad.git --branch metal-cdll
        cd tinygrad
        pip install -e .
    - name: Setup upterm session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true